general:
  debug: false
logging:
  level: info

# Rest Guard Client config
# rest:
#   reqs_timeout: 120
#   max_idle_conns: 10
#   idle_conn_timeout: 30
#   max_conns4host: 5
#   max_idleconns4host: 30
#   disable_compression: false
#   insecure_skip: false


# Authentication
# authentication:
#   github.com:
#      token: mytoken

# ---------------------------------------------
# Tarball flows configuration section
# if not defined in JobSource or JobOutput.
# ---------------------------------------------
# tar_flows:
#
#   Enable mutex for parallel creation of directories
#   in the untar specs. Normally this field must be
#   set to true, the default value.
#   mutex4dir: true
#
#   Define the max number of open files related
#   to a single untar operation. Be carefour on
#   set this option with a big value to avoid
#   'too open files' errors.
#   In a normal system this could be also 512.
#  max_openfiles: 100
#
#   Define the buffer size in KB to use
#   on create files from tar content.
#  copy_buffer_size: 32
#
#   Additional validate step on unpack phase.
#  validate: false
