sources:
# We need this to inherit the eclass used for kit cache JSON generation
- name: "core-kit"
  url: "https://github.com/macaroni-os/core-kit"
  branch: "mark-unstable"

target:
  name: my-kit
  url: "https://github.com/macaroni-os/my-kit"
  branch: mark-unstable

  atoms:
    - pkg: dev-util/myfoo

